apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "google-custom-search-mcp.fullname" . }}
  labels:
    {{- include "google-custom-search-mcp.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.pod.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "google-custom-search-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "google-custom-search-mcp.selectorLabels" . | nindent 8 }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.pod.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- include "google-custom-search-mcp.envVars" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.serviceAccount.existingFile.enabled }}
          volumeMounts:
            - name: google-service-account
              mountPath: /etc/google-service-account
              readOnly: true
          {{- end }}
      {{- if .Values.serviceAccount.existingFile.enabled }}
      volumes:
        - name: google-service-account
          secret:
            secretName: {{ include "google-custom-search-mcp.fullname" . }}-service-account
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}